server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/order_header?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: password
    username: orderuser
  sql:
    init:
      mode: always
  flyway:
    user: orderadmin
    password: password
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}

logging:
  level:
    org.hibernate.type.descriptor.sql: trace